# Generated by Django 4.1.4 on 2022-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('item_category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
