# Generated by Django 4.1.4 on 2022-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_from', models.TextField()),
                ('direction_to', models.TextField()),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(db_column='is active')),
                ('date_modified', models.DateField()),
                ('date_added', models.DateField()),
            ],
            options={
                'db_table': 'predefined_routes',
                'managed': False,
            },
        ),
    ]
